services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - .docker/app/php.ini:/usr/local/etc/php/php.ini
    environment:
      - PHP_MEMORY_LIMIT=256M
    networks:
      - laravel

  nginx:
    image: nginx:stable
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_management
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge